### ISSUE TITLE
Any chance to use Blender to design and use the mesh directly?

### ISSUE THREAD

**Issue by j2l** [DMST1990/ToOptixUpdate#11]
Fantastic, your plugin works fine in Blender 2.83B on Ubuntu 19.10 too! 
So far I tested one example only :)

Now .inp mesh is coming from FreeCAD. Is there any chance to be able to design the mesh in Blender and use it into ToOptix add-on?

Best would be to have FEM within Blender then you sculpt to remove "blue" material :)
https://github.com/sgrogan/FreeCAD/releases/tag/PY3.7-win

**Comment by Foxelmanian** [comment]
Hi @j2l ,

its possible to design your FEM-Model in Blender. 
Therfore i have to rewrite the addon.
You have to design a volumetric mesh in blender.

Give me some time :)

**Comment by j2l** [comment]
Sure :)
Thank you Martin!

**Comment by j2l** [comment]
Hope you're fine.
Any news?
Please, please, rewrite it, I gave you some time :)

**Comment by Foxelmanian** [comment]
Yea currently I am working on embedding a direct solver for python for multi criteria optimization, 
so it should be possible to build directly the model in blender.
I always have to take care on license and patent problems,
 so that I need to wait until the module are published in some sort of publicaiton.

**Comment by j2l** [comment]
Ah, ok, I see.
Thank you very much for detailing the process and your work.
Can't wait to see it!
Have a great day,

**Comment by j2l** [comment]
4 years and still waiting :smile_cat: 
Can you please have a look?

**Comment by Foxelmanian** [comment]
Hi due some lack of income,
i can not further proceed on this project.

But you can use as an alternative:
https://github.com/calculix/beso

Sorry for waiting for this Addon.

**Comment by j2l** [comment]
I totally understand. Thank you for your prompt reply, your link, and sharing your situation that I understand too well.
