### ISSUE TITLE
.idea sub directories?

### ISSUE THREAD

**Issue by joha2** [DMST1990/ToOptixUpdate#3]
The .idea sub directories are from your IDE, aren't they? Maybe they are also not useful for others and should be deleted in the git versioning itself. In particular they leak more or less private information about you: Like the files you edited with your IDE or the path structure. I don't know whether this was your intention.

For deleting them and ignoring them in the future: just add `.idea/` to the `.gitignore` file and copy this subfolder to another directory temporarily. Then perform `git rm -rf .idea/` such that they are removed from the index and copy the files back from the temporary location. Maybe there is a more `git` possibility to do that, but I don't know :-)

**Comment by Foxelmanian** [comment]
Thanks,

Yes they are from the IDE,
I just need so specify that wont be uploaded. 

I will correct that during restructuring the project.

Best Regards

Martin

**Comment by joha2** [comment]
Shouldn't be a problem anymore, once accepting the Pull Request and adding this line to the .gitignore file :-) See PR #6 :-)

**Comment by Foxelmanian** [comment]
Thanks :)
