### ISSUE TITLE
Blender Addon does not work

### ISSUE THREAD

**Issue by miho** [DMST1990/ToOptixUpdate#5]
Hi,

I am very interested in this project. But unfortunately, the Blender addon doesn't work for me.

I am using Windows 10, Blender 2.8 and FreeCAD 0.17.

Here's the output:

![image](https://user-images.githubusercontent.com/225266/62412505-b89d8980-b603-11e9-9d72-7165bd013c41.png)

**Comment by Foxelmanian** [comment]
Hi,

this Error is known. The Addon was designed for 2.79. I am still on creating an addon for 2.8. (The official release of Blender 2.8 was i think 1-2 weeks ago).

If you dont want to wait for the new Addon you can still use Blender 2.79

Best Regards

**Comment by miho** [comment]
Thanks for your quick response. I just updated to 2.8 since the readme claims that only 2.8 is supported. Using Blender 2.79 is fine for me.

**Comment by miho** [comment]
With Blender 2.79 I get an error during the activation of the addon. Are there additional steps necessary that I might have missed? I just copied the BlenderAddon folder to the scripts/addons/ folder inside my blender installation.

Here's the error I am seeing now:

![image](https://user-images.githubusercontent.com/225266/62414592-cb24bc80-b61d-11e9-9674-d69cfd3c8dcc.png)

**Comment by Foxelmanian** [comment]
Hi @miho 
just give me until tomorrow. 
I have got several issues and i have to implement these. On that trace I cant see an error.

If you have some error like this, you can start Blender on the command line. Then you will get the full error trace.

**Comment by joha2** [comment]
Maybe we can maintain macro compatibility between different blender version by using a version guard like:
```Python
from bpy.app import version
(major, minor, bugfix) = version
print("Blender version detection: " , major, minor, bugfix)
is_blen_280 = (major == 2 and minor == 80)
is_blen_279 = (major == 2 and minor == 79)
```

**Comment by Foxelmanian** [comment]
Hi @miho 

I tested the Addon for the version 2.80 and it worked quite well.

Currently only 2.80 is supported due to the usuage of python3.7. 
Blender 2.79 uses only Python 3.5, which can not handle some format methods.

So you need to use Blender 2.80, but this should work.

I tested the addon

https://github.com/DMST1990/ToOptixBlenderAddon

Maybe the Pad_Mesh.inp didnt work.

Try to test the two test files which are located in test\TestData of ToOptixCore
