### ISSUE TITLE
 Error in running "TwoRectanglesStruc.inp"

### ISSUE THREAD

**Issue by 461353349** [DMST1990/ToOptixUpdate#7]
When I run the "TwoRectanglesStruc.inp", Errors are as following. I donnot know what is the wrong.

D:\Project\Optimization\PyCharmWork\Scripts\python.exe D:/Project/ToOptiX/ToOptixUpdate/ToOptix_Python/run_optimization.py
Start topology otpimization
['70000.', ' 0.33']
No design space is active with 0 elements
D:/Project/ToOptiX/ccx/ccx.exe D:\Project\ToOptiX\ToOptixUpdate\ToOptix_Python\work\U_system_optimization

************************************************************

CalculiX Version 2.10, Copyright(C) 1998-2015 Guido Dhondt
CalculiX comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
certain conditions, see gpl.htm

************************************************************

You are using an executable made on Sa 5. Mär 12:23:33 CET 2016

  The numbers below are estimated upper bounds

  number of:

   nodes:        24958
   elements:        12228
   one-dimensional elements:            0
   two-dimensional elements:            0
   integration points per element:            1
   degrees of freedom per node:            3
   layers per element:            1

   distributed facial loads:          150
   distributed volumetric loads:            0
   concentrated loads:            0
   single point constraints:          306
   multiple point constraints:            1
   terms in all multiple point constraints:            1
   tie constraints:            0
   dependent nodes tied by cyclic constraints:            0
   dependent nodes in pre-tension constraints:            0

   sets:           10
   terms in all sets:       111860

   materials:           11
   constants per material and temperature:            2
   temperature points per material:            1
   plastic data points per material:            0

   orientations:            0
   amplitudes:            2
   data points in all amplitudes:            2
   print requests:            1
   transformations:            0
   property cards:            0

 *WARNING reading *STEP: parameter not recognized:
          NAME=STEP-1
 *WARNING reading *STEP. Card image:
          *STEP,NAME=STEP-1,NLGEOM=NO

 *WARNING reading *STEP: parameter not recognized:
          NLGEOM=NO
 *WARNING reading *STEP. Card image:
          *STEP,NAME=STEP-1,NLGEOM=NO

 *WARNING reading *EL PRINT: elementset EVOLUMES does not exist
 *WARNING in calinput. Card image cannot be interpreted:
 *WARNING reading the input file. Card image:
          ENER

 STEP            1

 Static analysis was selected

 Decascading the MPC's

 Determining the structure of the matrix:
 number of equations
 74568
 number of nonzero lower triangular matrix elements
 1949016

 Using up to 6 cpu(s) for the stress calculation.

 Using up to 6 cpu(s) for the symmetric stiffness/mass contributions.

 Factoring the system of equations using the symmetric spooles solver
 Using 1 cpu for spooles.

 Using up to 6 cpu(s) for the stress calculation.

 Job finished

Traceback (most recent call last):
  File "D:/Project/ToOptiX/ToOptixUpdate/ToOptix_Python/run_optimization.py", line 47, in <module>
    files, workDir, solverPath, cpus, no_design_set)
  File "D:/Project/ToOptiX/ToOptixUpdate/ToOptix_Python/run_optimization.py", line 26, in run_optimization
    opti_controller.run()
  File "D:\Project\ToOptiX\ToOptixUpdate\ToOptix_Python\TopologyOptimizer\OptimizationController.py", line 106, in run
    self.__optimization(file, fem_body, ele_filter, solution_type)
  File "D:\Project\ToOptiX\ToOptixUpdate\ToOptix_Python\TopologyOptimizer\OptimizationController.py", line 291, in __optimization
    frd_reader.get_displacement(fem_body.get_nodes())
  File "D:\Project\ToOptiX\ToOptixUpdate\ToOptix_Python\TopologyOptimizer\FEMPy\CCXPhraser.py", line 273, in get_displacement
    disp_y = float(line[25:37])
ValueError: could not convert string to float: '1-9.46471E-0'

Process finished with exit code 1

**Comment by Foxelmanian** [comment]
Hi @461353349  

something went wrong during parsing the results from Calculix. Currently the optimization was tested on ccx (2.8) and ccx (2.15). Maybe the export of the displacements in CalculiX has changed a little bit.

You are familiar with python, so that  I would reccomend, that you should clone the repostiroy
https://github.com/DMST1990/ToOptixCore


Just run the python script run_optimization*.py
Does this run with standard configuration?

In the .json file
you need to specify the ccx path

{
    "ccx_path": ".\\ccx.exe",
    "work_path": "work",
    "cpus": 6
}

**Comment by 461353349** [comment]
@DMST1990 Thanks for your reply. I find the calculix whose version is 2.15. The process is good without errors.
