### ISSUE TITLE
Add Material very iteration

### ISSUE THREAD

**Issue by 461353349** [DMST1990/ToOptixUpdate#8]
I am a layman for the topology optimization. I think the topology optimization is seeking for minimum weight design, so material is deleting very iteration. But I notice that our method is adding material very iteration. Does this method has any advantages?

**Comment by Foxelmanian** [comment]
This method is derived from the standard method (SIMP) with some change in the material law for better convergeing.

Optimization problem:
Maximize: Stiffness
Restriction: Volumina ratio 
Restriction: Density between 0% and 100%

No topology optimization seeks for the minimum strain energy, or in other words for the maximum stiffness.
You as the user specifies how much material should be used. So we dont minimize the amount of material. We want to maximize the stiffnes under a certian volumina ratio.

It should only add a small amount of material. So if you choose a volumina ratio of 30% (0.3) then it should be between 35% and 25%.

Typically it can increase the amount of material, if it locates better positions for the material.

**Comment by 461353349** [comment]
Thanks very much!
